language: node_js
node_js:
- '7'
before_install:
- npm install -g npm@'^5.10.0'
- npm install -g RadonApp/radon-extension-build#$TRAVIS_BRANCH || npm install -g RadonApp/radon-extension-build#develop
install:
- neb travis:install $TRAVIS_BRANCH
- neb package:validate
- git diff --exit-code
script:
- npm run build
- npm run travis:test
- npm run travis:coverage
- npm run travis:lint
- if [ ! -f ./Build/Coverage/lcov.info ]; then exit 1; fi
after_success:
- npm install -g coveralls
- cat ./Build/Coverage/lcov.info | coveralls
deploy:
- provider: releases
  draft: true
  skip_cleanup: true
  api_key:
    secure: A0pnsJ5UssDwtUibq4U67+N/7GeAHipomJ6alSEMG2d6TjqYnVFViKPgobN5gVpVG2fHFb3itrBl8KlII6Aijcw5WWKCJKeysL12zWs+BvUvB5zF2w6GmOENis3gLwrR2d9Ia8KRufITzLMH5/JCDtcgU2aPZSe9lZWeZvrjQps=
  file_glob: true
  file: Build/Production/Radon*.zip
  on:
    repo: RadonApp/radon-extension-firefox
    tags: true
- provider: bintray
  skip_cleanup: true
  key:
    secure: bWn2di+zvWltGHYUfl2C4j50yMU7XNeoDGiSnYLmgu/7FxxWuW94ZVQ3vc2n0VCFd5B5HpjKn8nC4mK2inpWzz/5O7aRDnr/4VjYyOgaAMxGtteJbiMIoozgbUiZbhWMoCX2oeZg5kQ2LqUiz6PylpYtx5uWH0ZIkt3D2GNtOz4=
  file: Build/Production/bintray.json
  user: neapp-ci
  on:
    repo: RadonApp/radon-extension-firefox
    all_branches: true
